/**
 * Site Configuration
 *
 * This file contains all site-specific settings that can be customized
 * for different niches (Fashion, Fitness, Food, Tech, etc.)
 *
 * GENERATED FILE - Do not edit manually
 * Generated by: Site Generator
 * Generated at: 2025-11-07T15:26:31.763Z
 */

import { getLanguageConfig, type SupportedLanguage } from './languages';

export interface SiteConfig {
  // Basic Site Information
  site: {
    name: string;
    tagline: string;
    description: string;
    url: string;
    wordpressUrl: string;
    language: string;
    locale: string;
  };

  // Brand Identity
  brand: {
    colors: {
      primary: string;
      secondary: string;
      accent: string;
      background: string;
      text: string;
      textSecondary?: string;
    };
    typography: {
      headingFont: string;
      bodyFont: string;
    };
    logo?: {
      text: string;
      subtitle?: string;
    };
  };

  // Content Settings
  content: {
    postsPerPage: number;
    relatedPostsCount: number;
    excerptLength: number;
    featuredImageRatio: string;
    showAuthor: boolean;
    showDate: boolean;
    showCategories: boolean;
    showTags: boolean;
  };

  // Navigation
  navigation: {
    header: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
    footer: {
      sections: Array<{
        title: string;
        links: Array<{
          label: string;
          href: string;
          external?: boolean;
        }>;
      }>;
    };
    menuCategories?: Array<{
      name: string;
      slug: string;
    }>;
  };

  // Social Media
  social: {
    pinterest?: string;
    instagram?: string;
    facebook?: string;
    twitter?: string;
    youtube?: string;
    tiktok?: string;
    email?: string;
  };

  // Analytics & Tracking
  analytics: {
    googleAnalytics?: string;
    googleAdsense?: string;
    facebookPixel?: string;
    pinterestTag?: string;
  };

  // Legal Information
  legal: {
    companyName: string;
    contactEmail: string;
    country: string;
    jurisdiction: string;
  };

  // Hero Section (Homepage)
  hero: {
    title: string;
    subtitle: string;
    backgroundImage: string;
    cta?: {
      text: string;
      href: string;
    };
  };

  // Persona / About Page
  persona?: {
    name: string;
    role: string;
    bio: string;
    story: string;
    expertise: string[];
    image?: string;
    quote?: string;
    achievements?: string[];
  };

  // Features / Highlights
  features?: Array<{
    title: string;
    description: string;
    icon?: string;
  }>;

  // Custom Scripts/Code Injection
  customScripts?: {
    headScripts?: string;
    bodyStartScripts?: string;
    bodyEndScripts?: string;
  };

  // SEO Defaults
  seo: {
    titleTemplate: string;
    defaultTitle: string;
    defaultDescription: string;
    twitterHandle?: string;
  };
}

/**
 * Current Site Configuration
 */
export const siteConfig: SiteConfig = {
  site: {
    name: "CoutourChronicles",
    tagline: "Style Your Story, Live Beautiful",
    description: "Discover the latest fashion trends, beauty secrets, and expert style advice at ContourChronicles. Your daily destination for elegance, beauty tips, and fashion inspiration.",
    url: process.env.NEXT_PUBLIC_SITE_URL || "https://couturechronicles.com",
    wordpressUrl: process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace('/graphql', '') || "https://wp.couturechronicles.com",
    language: "en",
    locale: "en_US",
  },

  brand: {
    colors: {
      "primary": "#1e3a5f",
      "secondary": "#f5f1e8",
      "accent": "#8b6f47",
      "background": "#fdfcfa",
      "text": "#2d2d2d",
      "textSecondary": "#ffffff"
},
    typography: {
      "headingFont": "Cormorant Garamond",
      "bodyFont": "Inter"
},
    logo: {
      text: "COUTOURCHRONICLES",
      subtitle: "Style Your Story, Live Beautiful",
    },
  },

  content: {
    postsPerPage: 12,
    relatedPostsCount: 5,
    excerptLength: 160,
    featuredImageRatio: "3:2",
    showAuthor: true,
    showDate: true,
    showCategories: true,
    showTags: true,
  },

  navigation: {
    header: [
      {
            "label": "Home",
            "href": "/"
      },
      {
            "label": "About",
            "href": "/about"
      }
],
    footer: {
      sections: [
        {
                "title": "Explore",
                "links": [
                        {
                                "label": "Beauty",
                                "href": "/category/beauty"
                        },
                        {
                                "label": "Fashion",
                                "href": "/category/fashion"
                        }
                ]
        },
        {
                "title": "Legal",
                "links": [
                        {
                                "label": "Privacy Policy",
                                "href": "/privacy"
                        },
                        {
                                "label": "Terms of Service",
                                "href": "/terms"
                        },
                        {
                                "label": "Disclaimer",
                                "href": "/disclaimer"
                        }
                ]
        },
        {
                "title": "Follow",
                "links": [
                        {
                                "label": "Pinterest",
                                "href": "https://pinterest.com",
                                "external": true
                        }
                ]
        }
],
    },
    menuCategories: [
      {
            "name": "Beauty",
            "slug": "beauty"
      },
      {
            "name": "Fashion",
            "slug": "fashion"
      }
],
  },

  social: {
    pinterest: "https://pinterest.com",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    tiktok: "",
    email: "",
  },

  analytics: {
    // googleAnalytics: "",
    // googleAdsense: "",
  },

  customScripts: {
    headScripts: `<script defer data-domain="couturechronicles.com" src="https://stats.tripleadigital.de/js/script.js"></script>
`,
    // bodyStartScripts: "",
    // bodyEndScripts: "",
  },

  legal: {
    companyName: "Triple A Digital",
    contactEmail: "hey@coutourchronicles.com",
    country: "Germany",
    jurisdiction: "Germany",
  },

  hero: {
    "title": "Discover Your Style",
    "subtitle": "Fashion, Beauty & Lifestyle Inspiration",
    "backgroundImage": "/images/hero-bg.jpg",
    "cta": {
        "text": "Explore Now",
        "href": "#categories"
    }
},

  persona: {
    "name": "Isabella Moreau",
    "role": "Fashion Stylist & Beauty Curator",
    "bio": "A former fashion editor turned independent stylist, Isabella brings 15+ years of industry insight to women who refuse to be defined by age. She believes that true style is timeless, personal, and evolves beautifully with every decade.",
    "story": "My journey in fashion began in the most unexpected place—my grandmother's attic in Lyon, where I discovered trunks filled with perfectly preserved couture pieces from the 1960s. Running my fingers over the exquisite craftsmanship, I realized that true elegance transcends trends and time. This revelation shaped my entire career philosophy: style isn't about chasing youth; it's about celebrating who you are becoming.\n\nAfter spending over a decade in the fast-paced world of fashion magazines in Paris and New York, I noticed a troubling gap. The industry was obsessed with youth, yet the most stylish, confident women I knew were those who had lived, learned, and developed their personal aesthetic over time. At 38, I left my editor position to create something different—a space where sophistication meets practicality, where investment pieces are valued over fleeting trends.\n\nCouture Chronicles was born from late-night conversations with friends who felt invisible in their late thirties and beyond. We're done apologizing for taking up space. We invest in quality over quantity, we understand our bodies and what flatters them, and we've learned that confidence is the best accessory. My mission is to share the insider knowledge I've gathered—from understanding fabric quality to finding that perfect red lipstick that works with mature skin—so that you can curate a wardrobe and beauty routine that makes you feel powerful.\n\nToday, I split my time between my Paris apartment and New York studio, working with private clients and creating content that celebrates the refined, intentional approach to style that comes with experience. Because the truth is, we're not trying to look younger—we're trying to look like the best version of ourselves, right now.",
    "expertise": [
        "Capsule Wardrobe Curation",
        "Age-Appropriate Luxury Styling",
        "Skincare for Mature Skin",
        "Investment Piece Selection"
    ],
    "quote": "Elegance is not about being noticed, it's about being remembered.",
    "achievements": [
        "Former Senior Fashion Editor at Vogue Paris",
        "Styled over 200 private clients internationally",
        "Featured expert in Harper's Bazaar and Elle on timeless style"
    ]
},
  seo: {
    titleTemplate: "%s | CoutourChronicles",
    defaultTitle: "CoutourChronicles - Style Your Story, Live Beautiful",
    defaultDescription: "Discover the latest fashion trends, beauty secrets, and expert style advice at ContourChronicles. Your daily destination for elegance, beauty tips, and fashion inspiration.",
  },
};

/**
 * Helper function to get nested config values safely
 */
export function getConfigValue<T>(path: string, defaultValue?: T): T | undefined {
  const keys = path.split('.');
  let value: any = siteConfig;

  for (const key of keys) {
    if (value && typeof value === 'object' && key in value) {
      value = value[key];
    } else {
      return defaultValue;
    }
  }

  return value as T;
}

/**
 * Get language configuration for current site
 */
export function getLanguage() {
  const langCode = siteConfig.site.language as SupportedLanguage;
  return getLanguageConfig(langCode);
}

/**
 * Get translated UI strings
 */
export function t() {
  return getLanguage().ui;
}
